package main

import (
	"context"
	"fmt"
	"log"

	calculatorpb "github.com/soumitrachakravarti/g-rpc-tutorial/calculator/calculator-pb"
	"google.golang.org/grpc"
)

func main() {
	// Loggging Client
	fmt.Printf("Client running...")

	// Establish connection with host
	c, e := grpc.Dial("localhost:50051", grpc.WithInsecure())
	if e != nil {
		fmt.Printf("Couldn't establish connection with the host %v", e)
	}
	// Closing connection
	defer c.Close()

	// Connect with Calculator Client Service generated by the proto file
	cc := calculatorpb.NewCalculatorServiceClient(c)

	// Invoking the Sum Function
	doSum(cc)
}

// Sum Service logic
func doSum(cc calculatorpb.CalculatorServiceClient) {
	// Creating a request
	request := &calculatorpb.SumRequest{
		A: 10,
		B: 10,
	}
	// Passing request
	response, e := cc.Sum(context.Background(), request)
	if e != nil {
		log.Fatalf("Error while calling Sum RPC: %v", e)
	}
	// Logging output
	log.Printf("Response from Sum RPC :%v", response.Result)

}
